# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf76af9bffc3a81b2cefde14cf9f53071549fdd1199de723e2463e0dbfc9f42c56a83f5bde285ab65a1f4586e9c0229bcd5a0a057100e32f5154cfb0fb9a33e9

test:
  secret_key_base: 66b34dff8cb84005692073f227e69429ef0d8a1c39e992b687ea3cec5cd6360ae9809482052cdeffbbbb819f40319b44611a3f6cf57ed82e79e63566f58cf094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
